Change Google Recorder source to Uptodown
nikhilbadyal/docker-py-revanced pull request #277
Opened 2023-08-13 12:21 UTC by hlqviet

As there are mostly bundles on APKMirror for Google Recorder now, it won't be able to download the latest version when we don't specify one.

2023-08-13 16:39 UTC, nikhilbadyal commented
Let's keep name still as grecorder. So that it doesn't break other existing setups.

2023-08-13 16:40 UTC, nikhilbadyal requested changes

2023-08-13 16:40 UTC, nikhilbadyal commented on README.md
Let's keep name still as grecorder. So that it doesn't break other existing setups.

2023-08-13 19:44 UTC, hlqviet commented on README.md
Updated the uptodown downloader logic to keep the app name

2023-08-14 17:46 UTC, nikhilbadyal approved these changes

2023-08-14 17:47 UTC, nikhilbadyal commented
Thanks for the PR. Great work.

2023-08-14 17:47 UTC, merged